name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: CoffeShop  # Your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'  # Path to your web app project, defaults to the root

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pull the code from the repository

      # You can add any additional commands or setup steps you need here
      # For example, if you're using a different build system, or if you're just deploying static files

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_CLIENTID_COFFE }}  # Make sure the secret is correctly set
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  # Deploy the root directory or a subdirectory
